### ISSUE TITLE
Bugs 'NSInvalidArgumentException', reason: '*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Input buffer must be in an uncompressed format when outputSettings is not nil' when i  click publishBtn mute audio video.

### ISSUE THREAD

**Issue by nhocconbl1** [timelessg/TLStoryCamera#1]

**Comment by timelessg** [comment]
it's my mistake, the next commit will be fix it, 

fix code：
       if audioEnable {
            movieWriter?.shouldPassthroughAudio = audioEnable
            movieFile?.audioEncodingTarget = movieWriter
        }

**Comment by rahulson** [comment]
Hi @timelessg  
App is still crashing in iPhone 6 plus when i try to publish video 
If i comment below code then it  works fine
if audioEnable {
movieWriter?.shouldPassthroughAudio = audioEnable
movieFile?.audioEncodingTarget = movieWriter
}
