### ISSUE TITLE
iPhone X : Not going full screen camera

### ISSUE THREAD

**Issue by fparkar** [timelessg/TLStoryCamera#18]
For iPhone X, camera is not going full screen.

Is there any setting to do this or this will be an enhancement. Please let me know.

**Comment by timelessg** [comment]
Well,you can try modify captureView.frame like this
```
        if UIDevice.isX {
            let width = ceil(view.height * 9.0 / 16.0)
            let offsetX = (view.width - width) / 2
            captureView?.x = offsetX
            captureView?.width = width
        }
```

**Comment by fparkar** [comment]
Below is what I did & its working fine.

Define variable

    var previewLayer: AVCaptureVideoPreviewLayer?

And then inside `initCamera()` added below code.

    self.previewLayer = AVCaptureVideoPreviewLayer(session: (videoCamera?.captureSession)!)
    self.previewLayer?.videoGravity = AVLayerVideoGravity.resizeAspectFill
    self.previewLayer?.connection?.videoOrientation = .portrait

    self.layer.insertSublayer(self.previewLayer!, at: 0)
    self.previewLayer?.frame = (self.frame)
