### ISSUE TITLE
No Focus or Two Tap Camera Switch 

### ISSUE THREAD

**Issue by JayBone16** [timelessg/TLStoryCamera#2]
With the latest release of TLStoryCamera a few things have taken a step backward.

First off, focus does not exist anymore on the latest version for some reason. 

Second, recording or not you cannot tap the screen two times to make the camera switch.

**Comment by timelessg** [comment]
Some features are lost, since the code refactoring, I will fix it on the next commit. thanks your report

**Comment by JayBone16** [comment]
Hey, thanks!
I have to say this is a great open source git.
