### ISSUE TITLE
Can’t run when adding the project as sub-project

### ISSUE THREAD

**Issue by oferRounds** [timelessg/TLStoryCamera#21]
Successfully builds, but then on run time it crashes with the following error:

```
dyld: Library not loaded: @rpath/TLStoryCameraFramework.framework/TLStoryCameraFramework
  Referenced from: /var/containers/Bundle/Application/58611AD6-F3FB-48D3-85EE-9C92AB0F6E61/<app_file_name>.app/<app_name>
  Reason: image not found
```

**Comment by oferRounds** [comment]
Ok, was able to solve it by adding the framework on the `Embedded Binaries` section, but now: 
`let bundlePath = Bundle.main.path(forResource: "TLStoryCameraResources", ofType: "bundle")` on `TLStoryOverlayOutputView` returns nil, making the app crash

**Comment by oferRounds** [comment]
The link of `How to build this project` is broken...

**Comment by oferRounds** [comment]
Solved it eventually by adding the resource bundle itself to main project

**Comment by derens99** [comment]
How did you add the resource bundle to the main project? I'm having this same error, but i dont fully understand your solution. Could you explain more in depth? Thanks.

**Comment by oferRounds** [comment]
Hi :)
I mean drag it to your project, to be included as any of your self-created files
