### ISSUE TITLE
Image reEdit is not working. it not show old image. Its show camera view. I just change UIImageView.init(frame:self.bounds)

### ISSUE THREAD

**Issue by nhocconbl1** [timelessg/TLStoryCamera#3]
*** First throw call stack:
(0x191b991b8 0x1905d055c 0x191b9908c 0x19265102c 0x1002db5c0 0x1002db920 0x1002db9fc 0x1002dc254 0x100d7d258 0x100d7d218 0x100d8aaec 0x100d80ce0 0x100d8b088 0x100d8ce2c 0x100d8cb78 0x190c2b2a0 0x190c2ad8c)
libc++abi.dylib: terminating with uncaught exception of type NSException When I choice old video and click public_button .

**Comment by timelessg** [comment]
well, you can trying the last commit.I think it have been sovled. and thanks your feedback

**Comment by nhocconbl1** [comment]
Thank you, I think this is best source code for everyone.
