### ISSUE TITLE
Present TLStoryViewController from tap button

### ISSUE THREAD

**Issue by chinhndse03483** [timelessg/TLStoryCamera#4]
Can I present TLStoryViewController from action tab one button? Please help me.
You have great open source git. Thanks

**Comment by timelessg** [comment]
you can try doing it,but don't have close button for the moment.i will support it on the next commit
```
        let vc = TLStoryViewController()
        self.present(vc, animated: true) {
            vc.resumeCamera(open: true)
        }

```

**Comment by chinhndse03483** [comment]
Thanks, I will try 👍

**Comment by chinhndse03483** [comment]
"Value of type 'TLStoryViewController' has no member 'resumeCamera'"
I try to add your code, but error.

**Comment by GitMAM** [comment]
Hi there, Is the cancel button is not supported yet :) would you be able to do soon?

**Comment by timelessg** [comment]
I’m sorry, i can’t understand cancelButton what you say.could you give me more tip about this? and you can try doing something on storyViewClose() after tap closeButton @GitMAM

**Comment by GitMAM** [comment]
ah okay i got it thanks :)

**Comment by GitMAM** [comment]
when i try to launch the camera from a button with this : let vc = TLStoryViewController()
        self.present(vc, animated: true) {
            vc.resumeCamera(open: true)
        }

it takes 2 seconds for it to launch? is that normal?

**Comment by timelessg** [comment]
cameraStart() is a time-consuming operation.I suggest you keep an instance of the TLStoryViewController,like demo.@GitMAM

**Comment by wanglouin1990925** [comment]
Hello This opensource is great. I am using TLStoryCamera on my app btw it is taking about 2 seconds to launch camera.
Is there any way to speed up for it?

**Comment by wanglouin1990925** [comment]
as you mentioned above, in case i save instance of TLStoryViewController as Globally while app opening then it will not occur memory issue?

**Comment by timelessg** [comment]
@wanglouin1990925 thanks for your issue, and you can try this code,but the singleton will use 20MB memory
```
class share {
        static let sharedInstance = TLStoryViewController()
    }
```
I haven't thought of a better way now,if you have any idea,please tell me

**Comment by wanglouin1990925** [comment]
yeah I think usage of singleton is good way for now. I will let you know if i find out better way
Thanks
