### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by anhmuonnoi** [timelessg/TLStoryCamera#9]
When I writing text in video then heppen crash 
Unexpectedly found nil while unwrapping an Optional value

<img width="729" alt="screen shot 2018-03-31 at 14 52 03" src="https://user-images.githubusercontent.com/6723051/38161142-7928abf0-34f3-11e8-97f8-cb8552450c37.png">
<img width="729" alt="screen shot 2018-03-31 at 14 52 17" src="https://user-images.githubusercontent.com/6723051/38161143-79c1b7b4-34f3-11e8-84e3-69b7a4b305d8.png">

**Comment by timelessg** [comment]
Would you like to give me more info like ios version,steps of operation and call stack when crash,thanks for your feedback. @anhmuonnoi

**Comment by anhmuonnoi** [comment]
I run in ios 10.3, it happens when I press repeatedly on the text and done button
video : https://youtu.be/Iq-dCuddELY

**Comment by anhmuonnoi** [comment]
thank for fix, it is resolved (y)
